name: Clique no botão do readme

on:
 workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clique aqui
        uses: jonatasperaza/jonatasperaza@main
        with:
          count: 0
      - name: Atualizar o número de cliques
        run: |
          echo "O número atual de cliques é: $count"
          count=$((count + 1))
          echo "O novo número de cliques é: $count"
      - name: Commitar as alterações
        run: |
          git config --local user.email "jonatassilvaperaza@gmail.com"
          git config --local user.name "jonatasperaza"
          git add .
          git commit -m "Atualizar o número de cliques"
      - name: Enviar as alterações
        run: |
          git push origin master
