yaml
name: Readme Counter

on:
 push:
    branches:
      - main
 pull_request:
    types:
      - opened
      - synchronize

jobs:
 readme-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install requests

      - name: Increment counter
        run: |
          python .github/workflows/increment_counter.py
